name: pwsh-script

on:
  push:
  schedule:
    - cron: "0 4 * * *"

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          BUPT_USERNAME: ${{ secrets.BUPT_USERNAME }}
          BUPT_PASSWORD: ${{ secrets.BUPT_PASSWORD }}
        run: |
          ./main.ps1
